project_id = "aazekmjmdchnpndplmvc"

[functions.admin-auth]
verify_jwt = false

[functions.ai-search]
verify_jwt = false

[functions.send-verification-code]
verify_jwt = false

[functions.verify-email-code]
verify_jwt = false
